image: archlinux
packages:
  - wget
  - unzip
  - cpio
  - bc
  - rsync
secrets:
  - 0d06436c-bc8f-4f65-af13-cad62d4f1127

tasks:
  - build: |
      cd binaries
      ./build.sh -b x86_64

  - deploy: |
      cd binaries
      ./build.sh -d x86_64

