image: archlinux
packages:
  - wget
  - unzip
  - cpio
  - bc
  - rsync
secrets:
  - 0d06436c-bc8f-4f65-af13-cad62d4f1127

tasks:
  - setup: |
      echo "batuu.sevenbyte.org ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPNMmSHb2ALfwP1oC2oUlVkUTOMR/HooZUbH4YDMQS/k" > $HOME/.ssh/known_hosts

  - build: |
      cd binaries
      ./build.sh -b x86_64

  - deploy: |
      cd binaries
      ./build.sh -d x86_64

