name: build

on:
  push:
    branches:
    - master

jobs:
  build-x86:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Clone
      run: |
        ./build.sh -p
    - name: Build x86
      run: |
        ./build.sh -b x86

    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_KEY }}
        known_hosts: ${{ secrets.KNOWN_HOSTS }}

    - name: Copy x86 to server
      run: | 
        ./build.sh -d x86

  build-x86_64:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Clone
      run: |
        ./build.sh -p
    - name: Build x86_64
      run: |
        ./build.sh -b x86_64

    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_KEY }}
        known_hosts: ${{ secrets.KNOWN_HOSTS }}

    - name: Copy x86_64 to server
      run: | 
        ./build.sh -d x86_64

  build-aarch64:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Clone
      run: |
        ./build.sh -p
    - name: Build aarch64
      run: |
        ./build.sh -b aarch64

    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_KEY }}
        known_hosts: ${{ secrets.KNOWN_HOSTS }}

    - name: Copy aarch64 to server
      run: | 
        ./build.sh -d aarch64
